### PR TITLE
Priority remapping ? (do not merge!)

### PR DESCRIPTION
**Pull request by yyolk**
Wonderful CLI..

I am trying to wrap my head around the different priorities when interacting directly with the API - I still want to use 1-4 (highest is 1,4 is lowest & default) like I do on the main Todoist apps, but the implementation is pure and uses the API's preference (https://developer.todoist.com/sync/v7/#items)

screenshot: 
image

This PR is just a small attempt at showing what I mean, by no means is it a complete (or good 😅) Pull Request - please close after viewing.

### CODE REVIEW

**Comment by yyolk** [comment]
refs #49

**Comment by blindgaenger** [comment]
This confused me as well. How can I support here? @sachaos

**Comment by sachaos** [comment]
I'm planning to fix this in task for upgrading to Todoist v8 API.

**Comment by sachaos** [comment]
I fixed it in https://github.com/sachaos/todoist/pull/88

**Pull request closed without merging**
