### PR TITLE
Implemented a configurable date and datetime format

### PR DESCRIPTION
**Pull request by HacDan**
Fixes Issue: #169 

Implemented via the config file a way to configure the date and datetime format at runtime. Also updated the README to reflect this change.

### CODE REVIEW

**Comment by kenliu** [comment]
Hi @HacDan I tried testing out this PR but ran into some auth issues when trying to sync -- no idea what the cause is though. Could you try rebasing your branch and pushing this PR again and see if that helps?

**Comment by HacDan** [comment]
Rebased, and still working fine. There are no code changes that affect the auth, and the diff between them doesn't change. I did remove the package name from the imports. My tooling was adding it automatically. No reason for that here. 

Regarding your error, 410 Gone sounds like a misconfiguration or a change to the library itself. Maybe pointing to the wrong API? Could also be a caching issue.

**Comment by kenliu** [comment]
Let me pull the latest and test it again. If it still doesn't work, I'll take your word that it is working fine :) and merge it assuming that we'll resolve any issues after the fact.

**Comment by kenliu** [comment]
Works for me now, thanks for adding this feature!

**Pull request merged**
