### PR TITLE
Add today subcommand

### PR DESCRIPTION
**Pull request by elipavlov**

### CODE REVIEW

**Comment by strangeman** [comment]
`alias todo-cl-today='todoist s && todoist completed-list | grep `date +%y/%m/%d`'` produces the same output, but without any code changes. Are you sure it's necessary?

**Comment by elipavlov** [comment]
@strangeman, my intention to have something similar to what we have in the original GUI app, exactly "Today" tab:

Screenshot 2020-12-27 at 16 13 39

But, to be more precise, my PR adds alias to:
```bash
todoist list -f today
```

Of course we can use OS aliases and techniques like piping, but my intention is to add more similarity to GUI app, to provide people like me more or less the same UX as in GUI app.

**Comment by sachaos** [comment]
I prefer fewer sub-commands than many sub-commands.
I want to make this product simpler than easy.

**Comment by elipavlov** [comment]
Ok, no problem.

**Pull request closed without merging**
